### ISSUE TITLE
grandtier.com is MIA

### ISSUE THREAD

**Issue by chadwhitacre** [paulkachur/orthodox_calendar#2]
Any plans to bring it back? https://nycathedral.org/ is similarly affected.

https://grandtier.com/

<img width="852" alt="Screenshot 2024-01-23 at 7 35 45 PM" src="https://github.com/paulkachur/orthodox_calendar/assets/134455/ab0967e1-1696-48e0-8f43-9cfc16059f6a">

**Comment by nicholaskachur** [comment]
Hi Chad,

I'm sorry to inform you that Paul Kachur, the maintainer of this repo and the Grandtier website, died in mid-2023. He had been sick for some time battling a late-stage cancer. I'm his nephew and got to visit him in the hospital, but I do not know what continuity planning there was for the calendar, if there even was any.

If you are in an investigative mood, you might try to contact leadership at the Cathedral, perhaps using the Internet Archive to view their contact information on a cached page.

Best wishes,
Nicholas

**Comment by chadwhitacre** [comment]
Oh no! My condolences to you and your family, @nicholaskachur. How wonderful, though, that your uncle reposed on Pascha! Memory eternal! 🙏 ☦️

I [lost my father](https://singinghome.com/) in May, 2023. After he passed, I put a fair bit of effort into preserving [his website](https://whitacregreek.com/), and now here in 2024 I've been looking forward to returning to happier side projects. One of these is [a Gospel-reading app](https://www.gospeldesk.org/read/app/), which had used the API on grandtier.com. Poking around again, it looks like [Orthocal](https://orthocal.info/api/) may be my best bet? 🤔 I see your [Doxacal](https://github.com/nicholaskachur/doxacal) as well.

One way or another, it seems we can close this issue. Thanks for the reply. God bless!

**Comment by brianglass** [comment]
@nicholaskachur, I'm very sorry to hear about your uncle. I very much appreciated the work Paul did on this calendar and learned most of what I know about the church calendar by reading through Paul's code. May his memory be eternal!

I am the builder/maintainer of [orthocal.info](https://orthocal.info). The Orthocal database is largely copied from this project and as such provides most of the same information as grandtier and nycathedral, though does lack some of the customizations Paul had included in the nycathedral site. I am happy to work with anyone needing to find an alternative solution in the interim.

**Comment by nicholaskachur** [comment]
Thank you both for your kind words, Chad and Brian. It was lovely to have Paul as a role model in my journey to becoming a technologist, and it's great to see that his work was appreciated. I'm sorry for your loss, Chad, memory eternal!

Brian, I looked at your API documentation and output and it looks great. My Doxacal project never really got going, so I think Orthocal is the much better replacement. Best wishes with both of your projects!
